# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-18 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='\u0645\u062a\u0646 \u062f\u0631\u0628\u0627\u0631\u0647 \u0645\u0627')),
                ('tel', models.CharField(max_length=65, verbose_name='\u062a\u0644\u0641\u0646')),
                ('mobile', models.CharField(max_length=50, verbose_name='\u0645\u0648\u0628\u0627\u06cc\u0644')),
                ('address', models.CharField(max_length=250, verbose_name='\u0622\u062f\u0631\u0633')),
            ],
            options={
                'verbose_name': '\u062f\u0631\u0628\u0627\u0631\u0647 \u0645\u0627',
                'verbose_name_plural': '\u062f\u0631\u0628\u0627\u0631\u0647 \u0645\u0627',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.ImageField(default=b'images/gallery/defaults.jpg', upload_to=b'images/gallery/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u06a9\u0648\u0686\u06a9')),
                ('large_img', models.ImageField(default=b'images/gallery/defaults.jpg', upload_to=b'images/gallery/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u0628\u0632\u0631\u06af')),
                ('alt', models.CharField(default=b'', max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': '\u06af\u0627\u0644\u0631\u06cc \u062a\u0635\u0627\u0648\u06cc\u0631',
                'verbose_name_plural': '\u06af\u0627\u0644\u0631\u06cc \u062a\u0635\u0627\u0648\u06cc\u0631',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0646\u0627\u0645 \u0645\u062d\u0635\u0648\u0644')),
                ('model', models.CharField(max_length=100, verbose_name='\u0645\u062f\u0644 \u0645\u062d\u0635\u0648\u0644')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='\u0645\u0634\u062e\u0635\u0627\u062a')),
                ('price', models.IntegerField(default=0, verbose_name='\u0642\u06cc\u0645\u062a \u0645\u062f\u0644')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0645\u062d\u0635\u0648\u0644\u0627\u062a',
                'verbose_name_plural': '\u0645\u062d\u0635\u0648\u0644\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u062f\u0633\u062a\u0647 \u0627\u0635\u0644\u06cc')),
                ('text', models.CharField(default=b'', max_length=200, verbose_name='\u062a\u0648\u0636\u06cc\u062d \u06a9\u0648\u062a\u0627\u0647 \u062f\u0631 \u0645\u0648\u0631\u062f \u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc')),
                ('img', models.ImageField(default=b'images/gallery/defaults.jpg', upload_to=b'images/category/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc \u0645\u062d\u0635\u0648\u0644\u0627\u062a',
                'verbose_name_plural': '\u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc \u0645\u062d\u0635\u0648\u0644\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.ImageField(help_text=b'size(370px * 294px)', upload_to=b'images/productImages/', verbose_name='\ufe96\ufebb\ufeed\u06cc\ufead \u06a9\ufeed\u0686\u06a9')),
                ('big_img', models.ImageField(help_text=b'size(570px * 453px)', upload_to=b'images/productImages/', verbose_name='\ufe96\ufebb\ufeed\u06cc\ufead \u0628\u0632\u0631\u06af')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.Product', verbose_name='\u0645\u062d\u0635\u0648\u0644')),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': '\u062a\u0635\u0648\u06cc\u0631 \u0645\u062d\u0635\u0648\u0644\u0627\u062a',
                'verbose_name_plural': '\u062a\u0635\u0648\u06cc\u0631 \u0645\u062d\u0635\u0648\u0644\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='\u0646\u0627\u0645')),
                ('title', models.CharField(max_length=500, verbose_name='\u0633\u0645\u062a')),
                ('image', models.ImageField(blank=True, help_text=b'size(260*311)', null=True, upload_to=b'images/team/', verbose_name='\u062a\u0635\u0648\u06cc\u0631')),
                ('priority', models.IntegerField(default=1, verbose_name=b'\xd8\xaa\xd8\xb1\xd8\xaa\xdb\x8c\xd8\xa8 \xda\x86\xdb\x8c\xd8\xaf\xd9\x85\xd8\xa7\xd9\x86')),
            ],
            options={
                'verbose_name': '\u062a\u06cc\u0645 \u0641\u0646\u06cc',
                'verbose_name_plural': '\u062a\u06cc\u0645 \u0641\u0646\u06cc',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ProductCategory', verbose_name='\u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc \u0645\u062d\u0635\u0648\u0644\u0627\u062a'),
        ),
    ]
