# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='\u067e\u0631\u0633\u0634')),
                ('question_fa', models.TextField(null=True, verbose_name='\u067e\u0631\u0633\u0634')),
                ('question_ar', models.TextField(null=True, verbose_name='\u067e\u0631\u0633\u0634')),
                ('question_en', models.TextField(null=True, verbose_name='\u067e\u0631\u0633\u0634')),
                ('answer', models.TextField(verbose_name='\u067e\u0627\u0633\u062e')),
                ('answer_fa', models.TextField(null=True, verbose_name='\u067e\u0627\u0633\u062e')),
                ('answer_ar', models.TextField(null=True, verbose_name='\u067e\u0627\u0633\u062e')),
                ('answer_en', models.TextField(null=True, verbose_name='\u067e\u0627\u0633\u062e')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_at'],
                'verbose_name': '\u0633\u0624\u0627\u0644\u0627\u062a \u0645\u062a\u062f\u0627\u0648\u0644',
                'verbose_name_plural': '\u0633\u0624\u0627\u0644\u0627\u062a \u0645\u062a\u062f\u0627\u0648\u0644',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.ImageField(default=b'images/gallery/defaults.jpg', upload_to=b'images/gallery/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u06a9\u0648\u0686\u06a9')),
                ('large_img', models.ImageField(default=b'images/gallery/defaults.jpg', upload_to=b'images/gallery/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u0628\u0632\u0631\u06af')),
                ('alt', models.CharField(default=b'', max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('alt_fa', models.CharField(default=b'', max_length=100, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('alt_ar', models.CharField(default=b'', max_length=100, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('alt_en', models.CharField(default=b'', max_length=100, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': '\u06af\u0627\u0644\u0631\u06cc',
                'verbose_name_plural': '\u06af\u0627\u0644\u0631\u06cc',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0646\u0627\u0645 \u0645\u062d\u0635\u0648\u0644')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645 \u0645\u062d\u0635\u0648\u0644')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645 \u0645\u062d\u0635\u0648\u0644')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645 \u0645\u062d\u0635\u0648\u0644')),
                ('small_img', models.ImageField(default=b'images/products/defaults.jpg', help_text=b'size(370px * 294px)', upload_to=b'images/products/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u06a9\u0648\u0686\u06a9')),
                ('big_img', models.ImageField(default=b'images/products/defaults.jpg', help_text=b'size(570px * 453px)', upload_to=b'images/products/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u0628\u0632\u0631\u06af')),
                ('description', models.TextField(default=b'', verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a \u0645\u062d\u0635\u0648\u0644')),
                ('description_fa', models.TextField(default=b'', null=True, verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a \u0645\u062d\u0635\u0648\u0644')),
                ('description_ar', models.TextField(default=b'', null=True, verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a \u0645\u062d\u0635\u0648\u0644')),
                ('description_en', models.TextField(default=b'', null=True, verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a \u0645\u062d\u0635\u0648\u0644')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0645\u062d\u0635\u0648\u0644',
                'verbose_name_plural': '\u0645\u062d\u0635\u0648\u0644\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0646\u0627\u0645 \u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645 \u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645 \u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645 \u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc')),
            ],
            options={
                'verbose_name': '\u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc \u0645\u062d\u0635\u0648\u0644\u0627\u062a',
                'verbose_name_plural': '\u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc \u0645\u062d\u0635\u0648\u0644\u0627\u062a',
            },
        ),
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1200, verbose_name='\u0645\u062a\u0646')),
                ('text_fa', models.CharField(max_length=1200, null=True, verbose_name='\u0645\u062a\u0646')),
                ('text_ar', models.CharField(max_length=1200, null=True, verbose_name='\u0645\u062a\u0646')),
                ('text_en', models.CharField(max_length=1200, null=True, verbose_name='\u0645\u062a\u0646')),
                ('priority', models.IntegerField(verbose_name='\u062a\u0631\u062a\u06cc\u0628 \u0686\u06cc\u062f\u0645\u0627\u0646')),
            ],
            options={
                'verbose_name': '\u0634\u0639\u0627\u0631 \u062a\u0628\u0644\u06cc\u063a\u0627\u062a\u06cc',
                'verbose_name_plural': '\u0634\u0639\u0627\u0631 \u062a\u0628\u0644\u06cc\u063a\u0627\u062a\u06cc',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='\u0646\u0627\u0645')),
                ('name_fa', models.CharField(max_length=500, null=True, verbose_name='\u0646\u0627\u0645')),
                ('name_ar', models.CharField(max_length=500, null=True, verbose_name='\u0646\u0627\u0645')),
                ('name_en', models.CharField(max_length=500, null=True, verbose_name='\u0646\u0627\u0645')),
                ('post', models.CharField(default=b'', max_length=500, verbose_name='\u0633\u0645\u062a')),
                ('post_fa', models.CharField(default=b'', max_length=500, null=True, verbose_name='\u0633\u0645\u062a')),
                ('post_ar', models.CharField(default=b'', max_length=500, null=True, verbose_name='\u0633\u0645\u062a')),
                ('post_en', models.CharField(default=b'', max_length=500, null=True, verbose_name='\u0633\u0645\u062a')),
                ('image', models.ImageField(blank=True, help_text=b'size(260*311)', null=True, upload_to=b'images/team/', verbose_name='\u0639\u06a9\u0633')),
                ('priority', models.IntegerField(default=1, verbose_name='\u062a\u0631\u062a\u06cc\u0628 \u0686\u06cc\u062f\u0645\u0627\u0646')),
            ],
            options={
                'verbose_name': '\u062a\u06cc\u0645 \u0641\u0646\u06cc',
                'verbose_name_plural': '\u062a\u06cc\u0645 \u0641\u0646\u06cc',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productCat', to='myapp.ProductCategory', verbose_name='\u062f\u0633\u062a\u0647 \u0628\u0646\u062f\u06cc \u0645\u062d\u0635\u0648\u0644'),
        ),
    ]
