# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='متن درباره ما')),
                ('tel', models.CharField(max_length=65, verbose_name='تلفن')),
                ('mobile', models.CharField(max_length=50, verbose_name='موبایل')),
                ('address', models.CharField(max_length=250, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='تصویر کوچک')),
                ('large_img', models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='تصویر بزرگ')),
                ('alt', models.CharField(default='', max_length=100, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': 'گالری تصاویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('model', models.CharField(max_length=100, verbose_name='مدل محصول')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='مشخصات')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت مدل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='دسته اصلی')),
                ('text', models.CharField(default='', max_length=200, verbose_name='توضیح کوتاه در مورد دسته بندی')),
                ('img', models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/category/', verbose_name='تصویر دسته بندی')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'دسته بندی محصولات',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.ImageField(help_text='size(370px * 294px)', upload_to='images/productImages/', verbose_name='ﺖﺻﻭیﺭ کﻭچک')),
                ('big_img', models.ImageField(help_text='size(570px * 453px)', upload_to='images/productImages/', verbose_name='ﺖﺻﻭیﺭ بزرگ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.Product', verbose_name='محصول')),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': 'تصویر محصولات',
                'verbose_name_plural': 'تصویر محصولات',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='نام')),
                ('title', models.CharField(max_length=500, verbose_name='سمت')),
                ('image', models.ImageField(blank=True, help_text='size(260*311)', null=True, upload_to='images/team/', verbose_name='تصویر')),
                ('priority', models.IntegerField(default=1, verbose_name='ترتیب چیدمان')),
            ],
            options={
                'verbose_name': 'تیم فنی',
                'verbose_name_plural': 'تیم فنی',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ProductCategory', verbose_name='دسته بندی محصولات'),
        ),
    ]
