# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='post_fa',
        ),
    ]
