# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('file', models.FileField(upload_to=b'catalog/', verbose_name='\u0641\u0627\u06cc\u0644')),
            ],
            options={
                'verbose_name': 'catalog',
                'verbose_name_plural': 'catalog',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='big_img',
            field=models.ImageField(default=b'images/products/defaults.jpg', upload_to=b'images/products/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u0628\u0632\u0631\u06af'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_img',
            field=models.ImageField(default=b'images/products/defaults.jpg', help_text=b'size(500px * 334px)', upload_to=b'images/products/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u06a9\u0648\u0686\u06a9'),
        ),
    ]
