# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170602_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='title',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='file',
            field=models.FileField(upload_to=b'catalog/', verbose_name='file'),
        ),
    ]
