# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_team_post_fa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['created_at'], 'verbose_name': 'گالری', 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'دسته بندی محصولات', 'verbose_name_plural': 'دسته بندی محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصویر محصول'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'تیم فنی', 'verbose_name_plural': 'تیم فنی'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt',
            field=models.CharField(default='', max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='large_img',
            field=models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='تصویر بزرگ'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='small_img',
            field=models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='تصویر کوچک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ProductCategory', verbose_name='دسته بندی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, verbose_name='مدل محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات محصول'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/category/', verbose_name='تصویر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='text',
            field=models.CharField(default='', max_length=200, verbose_name='توضیح دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='big_img',
            field=models.ImageField(help_text='size(570px * 453px)', upload_to='images/productImages/', verbose_name='تصویر بزرگ'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.Product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='small_img',
            field=models.ImageField(help_text='size(370px * 294px)', upload_to='images/productImages/', verbose_name='تصویر کوچک'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, help_text='size(260*311)', null=True, upload_to='images/team/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=500, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post',
            field=models.CharField(default='', max_length=500, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_ar',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_en',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='سمت'),
        ),
        migrations.AlterField(
            model_name='team',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='ترتیب چیدمان'),
        ),
    ]
