# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170602_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': '\u06a9\u0627\u062a\u0627\u0644\u0648\u06af', 'verbose_name_plural': '\u06a9\u0627\u062a\u0627\u0644\u0648\u06af'},
        ),
        migrations.AddField(
            model_name='catalog',
            name='title',
            field=models.CharField(default=b'', max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='file',
            field=models.FileField(upload_to=b'catalog/', verbose_name='\u0641\u0627\u06cc\u0644'),
        ),
    ]
