# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170521_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['created_at'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Category'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Image'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='large_img',
            field=models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='large image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='small_img',
            field=models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='small image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ProductCategory', verbose_name='product category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=100, verbose_name='product model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, null=True, verbose_name='product specification'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/category/', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='text',
            field=models.CharField(default='', max_length=200, verbose_name='category description'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='big_img',
            field=models.ImageField(help_text='size(570px * 453px)', upload_to='images/productImages/', verbose_name='large image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='small_img',
            field=models.ImageField(help_text='size(370px * 294px)', upload_to='images/productImages/', verbose_name='small image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, help_text='size(260*311)', null=True, upload_to='images/team/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post',
            field=models.CharField(default='', max_length=500, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_ar',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_en',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='team',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='priority'),
        ),
    ]
