# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-21 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170521_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='post_fa',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='post'),
        ),
    ]
