# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170602_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=b'images/slides/defaults.jpg', upload_to=b'images/slides/', verbose_name='\u0639\u06a9\u0633')),
            ],
            options={
                'verbose_name': 'SlidesImages',
                'verbose_name_plural': 'SlidesImages',
            },
        ),
    ]
