# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_slidesimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_img', models.ImageField(default=b'images/products/defaults.jpg', help_text=b'size(500px * 334px)', upload_to=b'images/products/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u06a9\u0648\u0686\u06a9')),
                ('big_img', models.ImageField(default=b'images/products/defaults.jpg', upload_to=b'images/products/', verbose_name='\u062a\u0635\u0648\u06cc\u0631 \u0628\u0632\u0631\u06af')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Products Images',
            },
        ),
        migrations.AlterModelOptions(
            name='slidesimages',
            options={'verbose_name': 'Slides image', 'verbose_name_plural': 'Slides Images'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='big_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_img',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.Product', verbose_name='product'),
        ),
    ]
