# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170609_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'', max_length=100, verbose_name='\u0639\u0646\u0648\u0627\u0646')),
                ('text', models.TextField(verbose_name='\u0645\u062a\u0646')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'images/articles/', verbose_name='\u0639\u06a9\u0633')),
                ('link', models.URLField(verbose_name='source link')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
