# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170523_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fa',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fa',
            field=models.TextField(null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_ar',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='alt_fa',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='category name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='category name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='category name'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_fa',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
    ]
