# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['created_at'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='updated_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='articles',
            name='text_ar',
            field=models.TextField(null=True, verbose_name='\u0645\u062a\u0646'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_en',
            field=models.TextField(null=True, verbose_name='\u0645\u062a\u0646'),
        ),
        migrations.AddField(
            model_name='articles',
            name='text_fa',
            field=models.TextField(null=True, verbose_name='\u0645\u062a\u0646'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_ar',
            field=models.CharField(default=b'', max_length=100, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_en',
            field=models.CharField(default=b'', max_length=100, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_fa',
            field=models.CharField(default=b'', max_length=100, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
    ]
