# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20170524_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['created_at'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Category'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Team'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt_ar',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt_en',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='alt_fa',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='large_img',
            field=models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='large image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='small_img',
            field=models.ImageField(default='images/gallery/defaults.jpg', upload_to='images/gallery/', verbose_name='small image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='big_img',
            field=models.ImageField(default='images/products/defaults.jpg', help_text='size(570px * 453px)', upload_to='images/products/', verbose_name='large image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ProductCategory', verbose_name='product category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_img',
            field=models.ImageField(default='images/products/defaults.jpg', help_text='size(370px * 294px)', upload_to='images/products/', verbose_name='small image'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, help_text='size(260*311)', null=True, upload_to='images/team/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name_fa',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post',
            field=models.CharField(default='', max_length=500, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_ar',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_en',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='team',
            name='post_fa',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='team',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='priority'),
        ),
    ]
