# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-10 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170609_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidesimages',
            options={'verbose_name': '\u062a\u0635\u0648\u06cc\u0631 \u0627\u0633\u0644\u0627\u06cc\u062f', 'verbose_name_plural': '\u062a\u0635\u0627\u0648\u06cc\u0631 \u0627\u0633\u0644\u0627\u06cc\u062f\u0631'},
        ),
    ]
