# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20170524_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=b'', unique=True),
        ),
    ]
