# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20170610_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0646\u0627\u0645')),
                ('name_fa', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='\u0646\u0627\u0645')),
                ('tel', models.CharField(max_length=14, verbose_name='phone')),
                ('address', models.CharField(max_length=300, verbose_name='address')),
                ('address_fa', models.CharField(max_length=300, null=True, verbose_name='address')),
                ('address_ar', models.CharField(max_length=300, null=True, verbose_name='address')),
                ('address_en', models.CharField(max_length=300, null=True, verbose_name='address')),
                ('description', models.TextField(verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a \u0645\u062d\u0635\u0648\u0644')),
                ('description_fa', models.TextField(null=True, verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a \u0645\u062d\u0635\u0648\u0644')),
                ('description_ar', models.TextField(null=True, verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a \u0645\u062d\u0635\u0648\u0644')),
                ('description_en', models.TextField(null=True, verbose_name='\u062a\u0648\u0636\u06cc\u062d\u0627\u062a \u0645\u062d\u0635\u0648\u0644')),
                ('type', models.CharField(choices=[('Resellers', 'Resellers'), ('Representatives', 'Representatives')], max_length=30, verbose_name='type')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'dealership',
                'verbose_name_plural': 'dealerships',
            },
        ),
    ]
