# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170601_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=b'', verbose_name='description'),
        ),
    ]
