# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(default=b'', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(default=b'', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(default=b'', null=True, verbose_name='description'),
        ),
    ]
