# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-11 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20170611_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reference_title',
            field=models.CharField(default=b'', max_length=300, verbose_name='Reference title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(verbose_name='Reference link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default=b'', max_length=300, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(default=b'', max_length=300, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(default=b'', max_length=300, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_fa',
            field=models.CharField(default=b'', max_length=300, null=True, verbose_name='\u0639\u0646\u0648\u0627\u0646'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0639\u0631\u0636 \u062c\u063a\u0631\u0627\u0641\u06cc\u0627\u06cc\u06cc'),
        ),
        migrations.AlterField(
            model_name='dealership',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0637\u0648\u0644 \u062c\u063a\u0631\u0627\u0641\u06cc\u0627\u06cc\u06cc'),
        ),
    ]
