# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20170601_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1200, verbose_name='\u0645\u062a\u0646')),
                ('text_fa', models.CharField(max_length=1200, null=True, verbose_name='\u0645\u062a\u0646')),
                ('text_ar', models.CharField(max_length=1200, null=True, verbose_name='\u0645\u062a\u0646')),
                ('text_en', models.CharField(max_length=1200, null=True, verbose_name='\u0645\u062a\u0646')),
                ('priority', models.IntegerField(verbose_name='\u062a\u0631\u062a\u06cc\u0628 \u0686\u06cc\u062f\u0645\u0627\u0646')),
                ('priority_fa', models.IntegerField(null=True, verbose_name='\u062a\u0631\u062a\u06cc\u0628 \u0686\u06cc\u062f\u0645\u0627\u0646')),
                ('priority_ar', models.IntegerField(null=True, verbose_name='\u062a\u0631\u062a\u06cc\u0628 \u0686\u06cc\u062f\u0645\u0627\u0646')),
                ('priority_en', models.IntegerField(null=True, verbose_name='\u062a\u0631\u062a\u06cc\u0628 \u0686\u06cc\u062f\u0645\u0627\u0646')),
            ],
        ),
    ]
