# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_slogan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slogan',
            options={'verbose_name': '\u0634\u0639\u0627\u0631 \u062a\u0628\u0644\u06cc\u063a\u0627\u062a\u06cc', 'verbose_name_plural': '\u0634\u0639\u0627\u0631 \u062a\u0628\u0644\u06cc\u063a\u0627\u062a\u06cc'},
        ),
    ]
