# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170601_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slogan',
            name='priority_ar',
        ),
        migrations.RemoveField(
            model_name='slogan',
            name='priority_en',
        ),
        migrations.RemoveField(
            model_name='slogan',
            name='priority_fa',
        ),
    ]
